version: '3'

services:
  web:
    image: oximeter:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/code
  postgres:
    image: postgres:bullseye
    ports:
      - "5432:5432" 
    volumes:
      - ./populate_local_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}