version: '3'

services:
  web:
    image: oximeter:latest
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  postgres-db:
    image: postgres:bullseye
    ports:
      - "5432:5432" 
    container_name: postgres-db
    volumes:
      - ./populate_local_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5